"""empty message

Revision ID: 0c7792999c79
Revises: f54d4ca6eafb
Create Date: 2018-09-14 11:39:07.040861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7792999c79'
down_revision = 'f54d4ca6eafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('Top', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'Top')
    # ### end Alembic commands ###
