"""empty message

Revision ID: a05e1a4af088
Revises: 0c7792999c79
Create Date: 2018-09-15 15:05:40.055771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05e1a4af088'
down_revision = '0c7792999c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('topic', sa.String(length=128), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('posts', 'topic')
    # ### end Alembic commands ###
