"""empty message

Revision ID: eb3e8090faca
Revises: 0c7792999c79
Create Date: 2018-09-16 20:31:27.261262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3e8090faca'
down_revision = '0c7792999c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('posts', 'topic')
    op.add_column('users', sa.Column('showaboutme', sa.Boolean(), nullable=True))
    #op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'showaboutme')
    op.add_column('posts', sa.Column('topic', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
