"""empty message

Revision ID: fb028797acb3
Revises: 0c7792999c79
Create Date: 2018-09-14 17:49:48.625141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb028797acb3'
down_revision = '0c7792999c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('top', sa.Integer(), nullable=True))
    op.drop_column('posts', 'Top')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('posts', sa.Column('Top', sa.INTEGER(), nullable=True))
    op.drop_column('posts', 'top')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
